=head1 NAME

dhandler - Directory handling assistant

=head1 SYNOPSIS

    python dhandler.py [-h] [--func FUNC]
                       --dfrom DFROM --dto DTO [--nopause]

=head1 DESCRIPTION

    dhandler provides functions that can facilitate directory handling.
    Currently available functions include:
        - deploy_dir
        - deploy_empty_subdirs

=head1 OPTIONS

    -h, --help
        Help message

    --func FUNC
        deploy_dir (default)
            Deploy dfrom, including its contents, to dto.
        deploy_empty_subdirs
            Deploy subdirectories of dfrom, excluding their contents, to dto.

    --dfrom DFROM
        The directory from which information will be retrieved

    --dto DTO
        The directory to which the retrieved information will be applied

    --nopause
        Do not pause the shell at the end of the program.

=head1 EXAMPLES

    --func adj_leading_spaces
        python dhandler.py --func deploy_dir --dfrom ./samples/sample3 --dto ./samples/sample3_deployed

    --func adj_leading_spaces
        python dhandler.py --func deploy_empty_subdirs --dfrom ./samples --dto ./samples/samples_unloaded

=head1 REQUIREMENTS

Python 3

=head1 SEE ALSO

L<fhandler - File handling assistant|https://github.com/jangcom/fhandler>

=head1 AUTHOR

Jaewoong Jang <jangj@korea.ac.kr>

=head1 COPYRIGHT

Copyright (c) 2020 Jaewoong Jang

=head1 LICENSE

This software is available under the MIT license;
the license information is found in 'LICENSE'.

=cut
